// The wording of plugins.nginxui.com. Capabilities and permissions use the
// words of Nginx UI, so the site and the marketplace describe them the same way.

export const LOCALES = ['en', 'zh_CN', 'zh_TW', 'ja_JP', 'ko_KR', 'de_DE', 'fr_FR', 'es', 'it_IT', 'pt_PT', 'ru_RU', 'uk_UA', 'tr_TR', 'vi_VN', 'ar']
// Languages written right to left.
export const RTL = ['ar']
export const LANG = { en: 'en', zh_CN: 'zh-CN', zh_TW: 'zh-TW', ja_JP: 'ja', ko_KR: 'ko', de_DE: 'de', fr_FR: 'fr', es: 'es', it_IT: 'it', pt_PT: 'pt-PT', ru_RU: 'ru', uk_UA: 'uk', tr_TR: 'tr', vi_VN: 'vi', ar: 'ar' }
export const LANGUAGE_NAME = { en: 'English', zh_CN: '简体中文', zh_TW: '繁體中文', ja_JP: '日本語', ko_KR: '한국어', de_DE: 'Deutsch', fr_FR: 'Français', es: 'Español', it_IT: 'Italiano', pt_PT: 'Português', ru_RU: 'Русский', uk_UA: 'Українська', tr_TR: 'Türkçe', vi_VN: 'Tiếng Việt', ar: 'العربية' }

export const STRINGS = {
  en: {
    title: 'Nginx UI Plugins',
    lead: 'Plugins that extend Nginx UI. To install one, open Plugins in Nginx UI and choose Marketplace.',
    search: 'Search plugins',
    empty: 'No plugin matches the search.',
    by: author => `By ${author}`,
    version: 'Version',
    beta: 'Beta',
    requires: version => `Nginx UI ${version} or later`,
    requiresLabel: 'Requires',
    platforms: 'Platforms',
    allPlatforms: 'All platforms',
    memory: 'Recommended memory',
    memoryShort: 'Memory',
    providers: count => `${count} DNS providers`,
    searchProviders: 'Search providers',
    repository: 'Repository',
    homepage: 'Homepage',
    releaseNotes: 'Release notes',
    trust: { official: 'Official', verified: 'Verified', community: 'Community' },
    submit: 'Submit a plugin',
    manage: 'Manage this plugin',
    manageNote: 'For its authors: versions, signers and listing changes in the developer portal.',
    guide: 'Developer guide',
    catalog: 'Catalog',
    updated: 'Updated',
    language: 'Language',
    darkMode: 'Dark mode',
    allPlugins: 'All plugins',
    categories: 'Categories',
    allCategories: 'All',
    close: 'Close',
    previous: 'Previous',
    next: 'Next',
    about: 'About',
    screenshots: 'Screenshots',
    provides: 'Provides',
    permissions: 'Requested permissions',
    noPermissions: 'This plugin needs no access beyond its own features.',
    onlyHosts: 'Only these addresses',
    authorNote: 'Note from the author',
    noHosts: 'No specific addresses listed',
    conflicts: names => `Cannot be enabled together with ${names.join(', ')}`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'Versions',
    latest: 'Latest',
    information: 'Information',
    id: 'ID',
    author: 'Author',
    license: 'License',
  },
  zh_CN: {
    title: 'Nginx UI 插件',
    lead: '为 Nginx UI 扩展功能的插件。安装时，在 Nginx UI 中打开“插件”并选择“市场”。',
    search: '搜索插件',
    empty: '没有符合搜索条件的插件。',
    by: author => `作者：${author}`,
    version: '版本',
    beta: '测试版',
    requires: version => `Nginx UI ${version} 或更高版本`,
    requiresLabel: '要求',
    platforms: '平台',
    allPlatforms: '所有平台',
    memory: '建议内存',
    memoryShort: '内存',
    providers: count => `${count} 个 DNS 服务商`,
    searchProviders: '搜索服务商',
    repository: '代码仓库',
    homepage: '主页',
    releaseNotes: '更新日志',
    trust: { official: '官方', verified: '已验证', community: '社区' },
    submit: '提交插件',
    manage: '管理此插件',
    manageNote: '供插件作者使用：在开发者中心管理版本、签名者与上架信息。',
    guide: '开发文档',
    catalog: '插件目录',
    updated: '更新于',
    language: '语言',
    darkMode: '深色模式',
    allPlugins: '全部插件',
    categories: '分类',
    allCategories: '全部',
    close: '关闭',
    previous: '上一张',
    next: '下一张',
    about: '简介',
    screenshots: '截图',
    provides: '提供',
    permissions: '请求的权限',
    noPermissions: '此插件除自身功能外不需要其他访问权限。',
    onlyHosts: '仅限以下地址',
    authorNote: '作者说明',
    noHosts: '未列出具体地址',
    conflicts: names => `不能与${names.map(name => `“${name}”`).join('、')}同时启用`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: '版本',
    latest: '最新',
    information: '信息',
    id: 'ID',
    author: '作者',
    license: '开源许可',
  },
  zh_TW: {
    title: 'Nginx UI 外掛',
    lead: '為 Nginx UI 擴充功能的外掛。安裝時，在 Nginx UI 中開啟「外掛」並選擇「市集」。',
    search: '搜尋外掛',
    empty: '沒有符合搜尋條件的外掛。',
    by: author => `作者：${author}`,
    version: '版本',
    beta: '測試版',
    requires: version => `Nginx UI ${version} 或更新版本`,
    requiresLabel: '需求',
    platforms: '平台',
    allPlatforms: '所有平台',
    memory: '建議記憶體',
    memoryShort: '記憶體',
    providers: count => `${count} 個 DNS 服務商`,
    searchProviders: '搜尋服務商',
    repository: '原始碼庫',
    homepage: '首頁',
    releaseNotes: '發行說明',
    trust: { official: '官方', verified: '已驗證', community: '社群' },
    submit: '提交外掛',
    manage: '管理此外掛',
    manageNote: '供外掛作者使用：在開發者中心管理版本、簽署者與上架資訊。',
    guide: '開發文件',
    catalog: '外掛目錄',
    updated: '更新於',
    language: '語言',
    darkMode: '深色模式',
    allPlugins: '全部外掛',
    categories: '分類',
    allCategories: '全部',
    close: '關閉',
    previous: '上一張',
    next: '下一張',
    about: '簡介',
    screenshots: '螢幕截圖',
    provides: '提供',
    permissions: '要求的權限',
    noPermissions: '此外掛除自身功能外不需要其他存取權限。',
    onlyHosts: '僅限以下位址',
    authorNote: '作者說明',
    noHosts: '未列出具體位址',
    conflicts: names => `不能與${names.map(name => `「${name}」`).join('、')}同時啟用`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: '版本',
    latest: '最新',
    information: '資訊',
    id: 'ID',
    author: '作者',
    license: '開源授權',
  },
  ja_JP: {
    title: 'Nginx UI プラグイン',
    lead: 'Nginx UI の機能を広げるプラグインです。インストールするには、Nginx UI で「プラグイン」を開き、「マーケットプレイス」を選びます。',
    search: 'プラグインを検索',
    empty: '検索に一致するプラグインはありません。',
    by: author => `著者：${author}`,
    version: 'バージョン',
    beta: 'ベータ版',
    requires: version => `Nginx UI ${version} 以降`,
    requiresLabel: '必要条件',
    platforms: 'プラットフォーム',
    allPlatforms: 'すべてのプラットフォーム',
    memory: '推奨メモリ',
    memoryShort: 'メモリ',
    providers: count => `DNS プロバイダー ${count} 件`,
    searchProviders: 'プロバイダーを検索',
    repository: 'リポジトリ',
    homepage: 'ホームページ',
    releaseNotes: 'リリースノート',
    trust: { official: '公式', verified: '検証済み', community: 'コミュニティ' },
    submit: 'プラグインを提出',
    manage: 'このプラグインを管理',
    manageNote: '作者向け：開発者ポータルでバージョン、署名者、掲載情報を管理します。',
    guide: '開発者ガイド',
    catalog: 'カタログ',
    updated: '更新日',
    language: '言語',
    darkMode: 'ダークモード',
    allPlugins: 'すべてのプラグイン',
    categories: 'カテゴリ',
    allCategories: 'すべて',
    close: '閉じる',
    previous: '前へ',
    next: '次へ',
    about: '概要',
    screenshots: 'スクリーンショット',
    provides: '提供する機能',
    permissions: '要求される権限',
    noPermissions: 'このプラグインは自身の機能以外へのアクセスを必要としません。',
    onlyHosts: 'これらのアドレスのみ',
    authorNote: '作者による説明',
    noHosts: '特定のアドレスは指定されていません',
    conflicts: names => `${names.map(name => `「${name}」`).join('、')}と同時に有効にできません`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'バージョン',
    latest: '最新',
    information: '情報',
    id: 'ID',
    author: '著者',
    license: 'ライセンス',
  },
  ko_KR: {
    title: 'Nginx UI 플러그인',
    lead: 'Nginx UI의 기능을 확장하는 플러그인입니다. 설치하려면 Nginx UI에서 "플러그인"을 열고 "마켓플레이스"를 선택하십시오.',
    search: '플러그인 검색',
    empty: '검색과 일치하는 플러그인이 없습니다.',
    by: author => `작성자: ${author}`,
    version: '버전',
    beta: '베타',
    requires: version => `Nginx UI ${version} 이상`,
    requiresLabel: '요구 사항',
    platforms: '플랫폼',
    allPlatforms: '모든 플랫폼',
    memory: '권장 메모리',
    memoryShort: '메모리',
    providers: count => `DNS 제공자 ${count}개`,
    searchProviders: '제공자 검색',
    repository: '저장소',
    homepage: '홈페이지',
    releaseNotes: '릴리스 노트',
    trust: { official: '공식', verified: '인증됨', community: '커뮤니티' },
    submit: '플러그인 제출',
    manage: '이 플러그인 관리',
    manageNote: '작성자용: 개발자 포털에서 버전, 서명자, 등록 정보를 관리합니다.',
    guide: '개발자 가이드',
    catalog: '카탈로그',
    updated: '업데이트',
    language: '언어',
    darkMode: '다크 모드',
    allPlugins: '모든 플러그인',
    categories: '카테고리',
    allCategories: '전체',
    close: '닫기',
    previous: '이전',
    next: '다음',
    about: '소개',
    screenshots: '스크린샷',
    provides: '제공 기능',
    permissions: '요청 권한',
    noPermissions: '이 플러그인은 자체 기능 외에는 접근 권한이 필요하지 않습니다.',
    onlyHosts: '다음 주소만',
    authorNote: '작성자 메모',
    noHosts: '지정된 주소 없음',
    conflicts: names => `${names.map(name => `"${name}"`).join(', ')}과(와) 함께 활성화할 수 없습니다`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: '버전',
    latest: '최신',
    information: '정보',
    id: 'ID',
    author: '작성자',
    license: '라이선스',
  },
  de_DE: {
    title: 'Nginx UI Plugins',
    lead: 'Plugins, die Nginx UI erweitern. Zum Installieren öffnen Sie in Nginx UI „Plugins“ und wählen „Marktplatz“.',
    search: 'Plugins suchen',
    empty: 'Kein Plugin entspricht der Suche.',
    by: author => `Von ${author}`,
    version: 'Version',
    beta: 'Beta',
    requires: version => `Nginx UI ${version} oder neuer`,
    requiresLabel: 'Erfordert',
    platforms: 'Plattformen',
    allPlatforms: 'Alle Plattformen',
    memory: 'Empfohlener Arbeitsspeicher',
    memoryShort: 'Speicher',
    providers: count => `${count} DNS-Anbieter`,
    searchProviders: 'Anbieter suchen',
    repository: 'Repository',
    homepage: 'Website',
    releaseNotes: 'Versionshinweise',
    trust: { official: 'Offiziell', verified: 'Verifiziert', community: 'Community' },
    submit: 'Plugin einreichen',
    manage: 'Dieses Plugin verwalten',
    manageNote: 'Für die Autoren: Versionen, Signierer und Eintrag im Entwicklerportal verwalten.',
    guide: 'Entwicklerhandbuch',
    catalog: 'Katalog',
    updated: 'Aktualisiert',
    language: 'Sprache',
    darkMode: 'Dunkler Modus',
    allPlugins: 'Alle Plugins',
    categories: 'Kategorien',
    allCategories: 'Alle',
    close: 'Schließen',
    previous: 'Zurück',
    next: 'Weiter',
    about: 'Über',
    screenshots: 'Screenshots',
    provides: 'Stellt bereit',
    permissions: 'Angeforderte Berechtigungen',
    noPermissions: 'Dieses Plugin benötigt keinen Zugriff über seine eigenen Funktionen hinaus.',
    onlyHosts: 'Nur diese Adressen',
    authorNote: 'Hinweis des Autors',
    noHosts: 'Keine bestimmten Adressen angegeben',
    conflicts: names => `Kann nicht zusammen mit ${names.map(name => `„${name}“`).join(', ')} aktiviert werden`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'Versionen',
    latest: 'Neueste',
    information: 'Informationen',
    id: 'ID',
    author: 'Autor',
    license: 'Lizenz',
  },
  fr_FR: {
    title: 'Plugins Nginx UI',
    lead: 'Des plugins qui étendent Nginx UI. Pour en installer un, ouvrez « Plugins » dans Nginx UI et choisissez « Marketplace ».',
    search: 'Rechercher des plugins',
    empty: 'Aucun plugin ne correspond à la recherche.',
    by: author => `Par ${author}`,
    version: 'Version',
    beta: 'Bêta',
    requires: version => `Nginx UI ${version} ou ultérieur`,
    requiresLabel: 'Nécessite',
    platforms: 'Plateformes',
    allPlatforms: 'Toutes les plateformes',
    memory: 'Mémoire recommandée',
    memoryShort: 'Mémoire',
    providers: count => `${count} fournisseurs DNS`,
    searchProviders: 'Rechercher des fournisseurs',
    repository: 'Dépôt',
    homepage: 'Page d\'accueil',
    releaseNotes: 'Notes de version',
    trust: { official: 'Officiel', verified: 'Vérifié', community: 'Communauté' },
    submit: 'Proposer un plugin',
    manage: 'Gérer ce plugin',
    manageNote: 'Pour ses auteurs : versions, signataires et fiche dans le portail des développeurs.',
    guide: 'Guide du développeur',
    catalog: 'Catalogue',
    updated: 'Mis à jour',
    language: 'Langue',
    darkMode: 'Mode sombre',
    allPlugins: 'Tous les plugins',
    categories: 'Catégories',
    allCategories: 'Toutes',
    close: 'Fermer',
    previous: 'Précédent',
    next: 'Suivant',
    about: 'À propos',
    screenshots: 'Captures d\'écran',
    provides: 'Fournit',
    permissions: 'Autorisations demandées',
    noPermissions: 'Ce plugin n\'a besoin d\'aucun accès en dehors de ses propres fonctionnalités.',
    onlyHosts: 'Uniquement ces adresses',
    authorNote: 'Note de l\'auteur',
    noHosts: 'Aucune adresse précise indiquée',
    conflicts: names => `Ne peut pas être activé en même temps que ${names.map(name => `« ${name} »`).join(', ')}`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'Versions',
    latest: 'Dernière',
    information: 'Informations',
    id: 'ID',
    author: 'Auteur',
    license: 'Licence',
  },
  es: {
    title: 'Plugins de Nginx UI',
    lead: 'Plugins que amplían Nginx UI. Para instalar uno, abra "Plugins" en Nginx UI y elija "Marketplace".',
    search: 'Buscar plugins',
    empty: 'Ningún plugin coincide con la búsqueda.',
    by: author => `Por ${author}`,
    version: 'Versión',
    beta: 'Beta',
    requires: version => `Nginx UI ${version} o posterior`,
    requiresLabel: 'Requiere',
    platforms: 'Plataformas',
    allPlatforms: 'Todas las plataformas',
    memory: 'Memoria recomendada',
    memoryShort: 'Memoria',
    providers: count => `${count} proveedores DNS`,
    searchProviders: 'Buscar proveedores',
    repository: 'Repositorio',
    homepage: 'Página principal',
    releaseNotes: 'Notas de la versión',
    trust: { official: 'Oficial', verified: 'Verificado', community: 'Comunidad' },
    submit: 'Enviar un plugin',
    manage: 'Gestionar este plugin',
    manageNote: 'Para sus autores: versiones, firmantes y ficha en el portal de desarrolladores.',
    guide: 'Guía para desarrolladores',
    catalog: 'Catálogo',
    updated: 'Actualizado',
    language: 'Idioma',
    darkMode: 'Modo oscuro',
    allPlugins: 'Todos los plugins',
    categories: 'Categorías',
    allCategories: 'Todas',
    close: 'Cerrar',
    previous: 'Anterior',
    next: 'Siguiente',
    about: 'Acerca de',
    screenshots: 'Capturas de pantalla',
    provides: 'Proporciona',
    permissions: 'Permisos solicitados',
    noPermissions: 'Este plugin no necesita ningún acceso aparte de sus propias funciones.',
    onlyHosts: 'Solo estas direcciones',
    authorNote: 'Nota del autor',
    noHosts: 'No se indican direcciones concretas',
    conflicts: names => `No se puede activar junto con ${names.map(name => `"${name}"`).join(', ')}`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'Versiones',
    latest: 'Última',
    information: 'Información',
    id: 'ID',
    author: 'Autor',
    license: 'Licencia',
  },
  it_IT: {
    title: 'Plugin di Nginx UI',
    lead: 'Plugin che estendono Nginx UI. Per installarne uno, aprire "Plugin" in Nginx UI e scegliere "Marketplace".',
    search: 'Cerca plugin',
    empty: 'Nessun plugin corrisponde alla ricerca.',
    by: author => `Di ${author}`,
    version: 'Versione',
    beta: 'Beta',
    requires: version => `Nginx UI ${version} o successivo`,
    requiresLabel: 'Richiede',
    platforms: 'Piattaforme',
    allPlatforms: 'Tutte le piattaforme',
    memory: 'Memoria consigliata',
    memoryShort: 'Memoria',
    providers: count => `${count} provider DNS`,
    searchProviders: 'Cerca provider',
    repository: 'Repository',
    homepage: 'Sito web',
    releaseNotes: 'Note di rilascio',
    trust: { official: 'Ufficiale', verified: 'Verificato', community: 'Community' },
    submit: 'Proponi un plugin',
    manage: 'Gestisci questo plugin',
    manageNote: 'Per gli autori: versioni, firmatari e scheda nel portale per sviluppatori.',
    guide: 'Guida per sviluppatori',
    catalog: 'Catalogo',
    updated: 'Aggiornato',
    language: 'Lingua',
    darkMode: 'Modalità scura',
    allPlugins: 'Tutti i plugin',
    categories: 'Categorie',
    allCategories: 'Tutte',
    close: 'Chiudi',
    previous: 'Precedente',
    next: 'Successivo',
    about: 'Informazioni',
    screenshots: 'Screenshot',
    provides: 'Fornisce',
    permissions: 'Autorizzazioni richieste',
    noPermissions: 'Questo plugin non richiede alcun accesso oltre alle proprie funzioni.',
    onlyHosts: 'Solo questi indirizzi',
    authorNote: 'Nota dell\'autore',
    noHosts: 'Nessun indirizzo specifico indicato',
    conflicts: names => `Non può essere attivato insieme a ${names.map(name => `"${name}"`).join(', ')}`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'Versioni',
    latest: 'Più recente',
    information: 'Dettagli',
    id: 'ID',
    author: 'Autore',
    license: 'Licenza',
  },
  pt_PT: {
    title: 'Plugins do Nginx UI',
    lead: 'Plugins que expandem o Nginx UI. Para instalar um, abra "Plugins" no Nginx UI e escolha "Marketplace".',
    search: 'Pesquisar plugins',
    empty: 'Nenhum plugin corresponde à pesquisa.',
    by: author => `Por ${author}`,
    version: 'Versão',
    beta: 'Beta',
    requires: version => `Nginx UI ${version} ou posterior`,
    requiresLabel: 'Requer',
    platforms: 'Plataformas',
    allPlatforms: 'Todas as plataformas',
    memory: 'Memória recomendada',
    memoryShort: 'Memória',
    providers: count => `${count} provedores DNS`,
    searchProviders: 'Pesquisar provedores',
    repository: 'Repositório',
    homepage: 'Página inicial',
    releaseNotes: 'Notas da versão',
    trust: { official: 'Oficial', verified: 'Verificado', community: 'Comunidade' },
    submit: 'Submeter um plugin',
    manage: 'Gerir este plugin',
    manageNote: 'Para os autores: versões, signatários e listagem no portal de programadores.',
    guide: 'Guia do programador',
    catalog: 'Catálogo',
    updated: 'Atualizado',
    language: 'Idioma',
    darkMode: 'Modo escuro',
    allPlugins: 'Todos os plugins',
    categories: 'Categorias',
    allCategories: 'Todas',
    close: 'Fechar',
    previous: 'Anterior',
    next: 'Seguinte',
    about: 'Sobre',
    screenshots: 'Capturas de ecrã',
    provides: 'Disponibiliza',
    permissions: 'Permissões pedidas',
    noPermissions: 'Este plugin não precisa de nenhum acesso além das suas próprias funcionalidades.',
    onlyHosts: 'Apenas estes endereços',
    authorNote: 'Nota do autor',
    noHosts: 'Nenhum endereço específico indicado',
    conflicts: names => `Não pode ser ativado em conjunto com ${names.map(name => `"${name}"`).join(', ')}`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'Versões',
    latest: 'Mais recente',
    information: 'Informações',
    id: 'ID',
    author: 'Autor',
    license: 'Licença',
  },
  ru_RU: {
    title: 'Плагины Nginx UI',
    lead: 'Плагины, расширяющие возможности Nginx UI. Чтобы установить плагин, откройте в Nginx UI раздел «Плагины» и выберите «Маркетплейс».',
    search: 'Поиск плагинов',
    empty: 'Нет плагинов, соответствующих запросу.',
    by: author => `Автор: ${author}`,
    version: 'Версия',
    beta: 'Бета',
    requires: version => `Nginx UI ${version} или новее`,
    requiresLabel: 'Требуется',
    platforms: 'Платформы',
    allPlatforms: 'Все платформы',
    memory: 'Рекомендуемая память',
    memoryShort: 'Память',
    providers: count => `DNS-провайдеров: ${count}`,
    searchProviders: 'Поиск провайдеров',
    repository: 'Репозиторий',
    homepage: 'Сайт',
    releaseNotes: 'Примечания к выпуску',
    trust: { official: 'Официальный', verified: 'Проверенный', community: 'Сообщество' },
    submit: 'Предложить плагин',
    manage: 'Управлять плагином',
    manageNote: 'Для авторов: версии, подписанты и карточка в портале разработчиков.',
    guide: 'Руководство разработчика',
    catalog: 'Каталог',
    updated: 'Обновлено',
    language: 'Язык',
    darkMode: 'Тёмная тема',
    allPlugins: 'Все плагины',
    categories: 'Категории',
    allCategories: 'Все',
    close: 'Закрыть',
    previous: 'Назад',
    next: 'Далее',
    about: 'О плагине',
    screenshots: 'Снимки экрана',
    provides: 'Предоставляет',
    permissions: 'Запрашиваемые разрешения',
    noPermissions: 'Этому плагину не нужен доступ за пределами его собственных функций.',
    onlyHosts: 'Только эти адреса',
    authorNote: 'Примечание автора',
    noHosts: 'Конкретные адреса не указаны',
    conflicts: names => `Нельзя включить одновременно с ${names.map(name => `«${name}»`).join(', ')}`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'Версии',
    latest: 'Последняя',
    information: 'Сведения',
    id: 'ID',
    author: 'Автор',
    license: 'Лицензия',
  },
  uk_UA: {
    title: 'Плагіни Nginx UI',
    lead: 'Плагіни, що розширюють можливості Nginx UI. Щоб установити плагін, відкрийте в Nginx UI розділ «Плагіни» та виберіть «Маркетплейс».',
    search: 'Пошук плагінів',
    empty: 'Немає плагінів, що відповідають запиту.',
    by: author => `Автор: ${author}`,
    version: 'Версія',
    beta: 'Бета',
    requires: version => `Nginx UI ${version} або новіша`,
    requiresLabel: 'Потрібно',
    platforms: 'Платформи',
    allPlatforms: 'Усі платформи',
    memory: 'Рекомендована пам\'ять',
    memoryShort: 'Пам\'ять',
    providers: count => `DNS-провайдерів: ${count}`,
    searchProviders: 'Пошук провайдерів',
    repository: 'Репозиторій',
    homepage: 'Сайт',
    releaseNotes: 'Примітки до випуску',
    trust: { official: 'Офіційний', verified: 'Перевірений', community: 'Спільнота' },
    submit: 'Запропонувати плагін',
    manage: 'Керувати плагіном',
    manageNote: 'Для авторів: версії, підписанти й картка в порталі розробників.',
    guide: 'Посібник розробника',
    catalog: 'Каталог',
    updated: 'Оновлено',
    language: 'Мова',
    darkMode: 'Темна тема',
    allPlugins: 'Усі плагіни',
    categories: 'Категорії',
    allCategories: 'Усі',
    close: 'Закрити',
    previous: 'Назад',
    next: 'Далі',
    about: 'Про плагін',
    screenshots: 'Знімки екрана',
    provides: 'Надає',
    permissions: 'Запитувані дозволи',
    noPermissions: 'Цьому плагіну не потрібен доступ поза межами його власних функцій.',
    onlyHosts: 'Лише ці адреси',
    authorNote: 'Примітка автора',
    noHosts: 'Конкретні адреси не вказано',
    conflicts: names => `Не можна ввімкнути одночасно з ${names.map(name => `«${name}»`).join(', ')}`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'Версії',
    latest: 'Остання',
    information: 'Відомості',
    id: 'ID',
    author: 'Автор',
    license: 'Ліцензія',
  },
  tr_TR: {
    title: 'Nginx UI Eklentileri',
    lead: 'Nginx UI\'ı genişleten eklentiler. Bir eklenti kurmak için Nginx UI\'da "Eklentiler"i açın ve "Pazar Yeri"ni seçin.',
    search: 'Eklenti ara',
    empty: 'Aramayla eşleşen eklenti yok.',
    by: author => `Geliştiren: ${author}`,
    version: 'Sürüm',
    beta: 'Beta',
    requires: version => `Nginx UI ${version} veya üzeri`,
    requiresLabel: 'Gereksinim',
    platforms: 'Platformlar',
    allPlatforms: 'Tüm platformlar',
    memory: 'Önerilen bellek',
    memoryShort: 'Bellek',
    providers: count => `${count} DNS sağlayıcısı`,
    searchProviders: 'Sağlayıcı ara',
    repository: 'Depo',
    homepage: 'Ana sayfa',
    releaseNotes: 'Sürüm notları',
    trust: { official: 'Resmî', verified: 'Doğrulanmış', community: 'Topluluk' },
    submit: 'Eklenti gönder',
    manage: 'Bu eklentiyi yönet',
    manageNote: 'Yazarları için: sürümler, imzalayanlar ve liste bilgileri geliştirici portalında.',
    guide: 'Geliştirici kılavuzu',
    catalog: 'Katalog',
    updated: 'Güncellendi',
    language: 'Dil',
    darkMode: 'Koyu mod',
    allPlugins: 'Tüm eklentiler',
    categories: 'Kategoriler',
    allCategories: 'Tümü',
    close: 'Kapat',
    previous: 'Önceki',
    next: 'Sonraki',
    about: 'Hakkında',
    screenshots: 'Ekran görüntüleri',
    provides: 'Sağladıkları',
    permissions: 'İstenen izinler',
    noPermissions: 'Bu eklenti kendi özellikleri dışında herhangi bir erişime ihtiyaç duymaz.',
    onlyHosts: 'Yalnızca bu adresler',
    authorNote: 'Geliştiricinin notu',
    noHosts: 'Belirli bir adres belirtilmemiş',
    conflicts: names => `${names.map(name => `"${name}"`).join(', ')} ile birlikte etkinleştirilemez`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'Sürümler',
    latest: 'En yeni',
    information: 'Bilgiler',
    id: 'Kimlik',
    author: 'Geliştirici',
    license: 'Lisans',
  },
  vi_VN: {
    title: 'Plugin Nginx UI',
    lead: 'Các plugin mở rộng Nginx UI. Để cài đặt, hãy mở "Plugin" trong Nginx UI và chọn "Chợ plugin".',
    search: 'Tìm plugin',
    empty: 'Không có plugin nào khớp với tìm kiếm.',
    by: author => `Tác giả: ${author}`,
    version: 'Phiên bản',
    beta: 'Beta',
    requires: version => `Nginx UI ${version} trở lên`,
    requiresLabel: 'Yêu cầu',
    platforms: 'Nền tảng',
    allPlatforms: 'Mọi nền tảng',
    memory: 'Bộ nhớ khuyến nghị',
    memoryShort: 'Bộ nhớ',
    providers: count => `${count} nhà cung cấp DNS`,
    searchProviders: 'Tìm nhà cung cấp',
    repository: 'Kho mã',
    homepage: 'Trang chủ',
    releaseNotes: 'Ghi chú phát hành',
    trust: { official: 'Chính thức', verified: 'Đã xác minh', community: 'Cộng đồng' },
    submit: 'Gửi plugin',
    manage: 'Quản lý plugin này',
    manageNote: 'Dành cho tác giả: phiên bản, người ký và thông tin niêm yết trong cổng nhà phát triển.',
    guide: 'Hướng dẫn cho nhà phát triển',
    catalog: 'Danh mục',
    updated: 'Cập nhật',
    language: 'Ngôn ngữ',
    darkMode: 'Chế độ tối',
    allPlugins: 'Tất cả plugin',
    categories: 'Thể loại',
    allCategories: 'Tất cả',
    close: 'Đóng',
    previous: 'Trước',
    next: 'Tiếp',
    about: 'Giới thiệu',
    screenshots: 'Ảnh chụp màn hình',
    provides: 'Cung cấp',
    permissions: 'Quyền yêu cầu',
    noPermissions: 'Plugin này không cần quyền truy cập nào ngoài các tính năng của chính nó.',
    onlyHosts: 'Chỉ các địa chỉ này',
    authorNote: 'Ghi chú của tác giả',
    noHosts: 'Không liệt kê địa chỉ cụ thể',
    conflicts: names => `Không thể bật cùng lúc với ${names.map(name => `"${name}"`).join(', ')}`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'Phiên bản',
    latest: 'Mới nhất',
    information: 'Thông tin',
    id: 'ID',
    author: 'Tác giả',
    license: 'Giấy phép',
  },
  ar: {
    title: 'إضافات Nginx UI',
    lead: 'إضافات توسّع إمكانات Nginx UI. لتثبيت إضافة، افتح «الإضافات» في Nginx UI واختر «المتجر».',
    search: 'البحث في الإضافات',
    empty: 'لا توجد إضافة تطابق البحث.',
    by: author => `بواسطة ${author}`,
    version: 'الإصدار',
    beta: 'تجريبي',
    requires: version => `Nginx UI ${version} أو أحدث`,
    requiresLabel: 'يتطلب',
    platforms: 'المنصات',
    allPlatforms: 'جميع المنصات',
    memory: 'الذاكرة الموصى بها',
    memoryShort: 'الذاكرة',
    providers: count => `${count} مزود DNS`,
    searchProviders: 'البحث في المزودين',
    repository: 'المستودع',
    homepage: 'الصفحة الرئيسية',
    releaseNotes: 'ملاحظات الإصدار',
    trust: { official: 'رسمي', verified: 'موثّق', community: 'المجتمع' },
    submit: 'إرسال إضافة',
    manage: 'إدارة هذه الإضافة',
    manageNote: 'لمؤلفيها: الإصدارات والموقّعون وبيانات الإدراج في بوابة المطورين.',
    guide: 'دليل المطوّرين',
    catalog: 'الكتالوج',
    updated: 'آخر تحديث',
    language: 'اللغة',
    darkMode: 'الوضع الداكن',
    allPlugins: 'جميع الإضافات',
    categories: 'الفئات',
    allCategories: 'الكل',
    close: 'إغلاق',
    previous: 'السابق',
    next: 'التالي',
    about: 'نبذة',
    screenshots: 'لقطات الشاشة',
    provides: 'يوفّر',
    permissions: 'الأذونات المطلوبة',
    noPermissions: 'لا تحتاج هذه الإضافة إلى أي وصول يتجاوز ميزاتها الخاصة.',
    onlyHosts: 'هذه العناوين فقط',
    authorNote: 'ملاحظة من المطوّر',
    noHosts: 'لم تُذكر عناوين محددة',
    conflicts: names => `لا يمكن تفعيلها مع ${names.map(name => `«${name}»`).join('، ')}`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'الإصدارات',
    latest: 'الأحدث',
    information: 'المعلومات',
    id: 'المعرّف',
    author: 'المطوّر',
    license: 'الترخيص',
  },
}

// The categories of schema/entry.schema.json, in the order the filter offers
// them. A category the site does not know shows its id.
export const CATEGORIES = {
  certificates: { en: 'Certificates', zh_CN: '证书', zh_TW: '憑證', ja_JP: '証明書', ko_KR: '인증서', de_DE: 'Zertifikate', fr_FR: 'Certificats', es: 'Certificados', it_IT: 'Certificati', pt_PT: 'Certificados', ru_RU: 'Сертификаты', uk_UA: 'Сертифікати', tr_TR: 'Sertifikalar', vi_VN: 'Chứng chỉ', ar: 'الشهادات' },
  dns: { en: 'DNS', zh_CN: 'DNS', zh_TW: 'DNS', ja_JP: 'DNS', ko_KR: 'DNS', de_DE: 'DNS', fr_FR: 'DNS', es: 'DNS', it_IT: 'DNS', pt_PT: 'DNS', ru_RU: 'DNS', uk_UA: 'DNS', tr_TR: 'DNS', vi_VN: 'DNS', ar: 'DNS' },
  security: { en: 'Security', zh_CN: '安全', zh_TW: '安全性', ja_JP: 'セキュリティ', ko_KR: '보안', de_DE: 'Sicherheit', fr_FR: 'Sécurité', es: 'Seguridad', it_IT: 'Sicurezza', pt_PT: 'Segurança', ru_RU: 'Безопасность', uk_UA: 'Безпека', tr_TR: 'Güvenlik', vi_VN: 'Bảo mật', ar: 'الأمان' },
  traffic: { en: 'Traffic and upstreams', zh_CN: '流量与上游', zh_TW: '流量與上游', ja_JP: 'トラフィックとアップストリーム', ko_KR: '트래픽과 업스트림', de_DE: 'Datenverkehr und Upstreams', fr_FR: 'Trafic et upstreams', es: 'Tráfico y upstreams', it_IT: 'Traffico e upstream', pt_PT: 'Tráfego e upstreams', ru_RU: 'Трафик и upstream', uk_UA: 'Трафік і upstream', tr_TR: 'Trafik ve upstream', vi_VN: 'Lưu lượng và upstream', ar: 'حركة المرور والخوادم الخلفية' },
  monitoring: { en: 'Monitoring', zh_CN: '监控', zh_TW: '監控', ja_JP: '監視', ko_KR: '모니터링', de_DE: 'Überwachung', fr_FR: 'Surveillance', es: 'Monitorización', it_IT: 'Monitoraggio', pt_PT: 'Monitorização', ru_RU: 'Мониторинг', uk_UA: 'Моніторинг', tr_TR: 'İzleme', vi_VN: 'Giám sát', ar: 'المراقبة' },
  logs: { en: 'Logs', zh_CN: '日志', zh_TW: '日誌', ja_JP: 'ログ', ko_KR: '로그', de_DE: 'Protokolle', fr_FR: 'Journaux', es: 'Registros', it_IT: 'Log', pt_PT: 'Registos', ru_RU: 'Журналы', uk_UA: 'Журнали', tr_TR: 'Günlükler', vi_VN: 'Nhật ký', ar: 'السجلات' },
  analytics: { en: 'Analytics', zh_CN: '分析', zh_TW: '分析', ja_JP: '分析', ko_KR: '분석', de_DE: 'Analyse', fr_FR: 'Analyse', es: 'Análisis', it_IT: 'Analisi', pt_PT: 'Análise', ru_RU: 'Аналитика', uk_UA: 'Аналітика', tr_TR: 'Analiz', vi_VN: 'Phân tích', ar: 'التحليلات' },
  notifications: { en: 'Notifications', zh_CN: '通知', zh_TW: '通知', ja_JP: '通知', ko_KR: '알림', de_DE: 'Benachrichtigungen', fr_FR: 'Notifications', es: 'Notificaciones', it_IT: 'Notifiche', pt_PT: 'Notificações', ru_RU: 'Уведомления', uk_UA: 'Сповіщення', tr_TR: 'Bildirimler', vi_VN: 'Thông báo', ar: 'الإشعارات' },
  backup: { en: 'Backup and storage', zh_CN: '备份与存储', zh_TW: '備份與儲存', ja_JP: 'バックアップとストレージ', ko_KR: '백업과 저장소', de_DE: 'Sicherung und Speicher', fr_FR: 'Sauvegarde et stockage', es: 'Copias de seguridad y almacenamiento', it_IT: 'Backup e archiviazione', pt_PT: 'Cópias de segurança e armazenamento', ru_RU: 'Резервное копирование и хранилище', uk_UA: 'Резервне копіювання та сховище', tr_TR: 'Yedekleme ve depolama', vi_VN: 'Sao lưu và lưu trữ', ar: 'النسخ الاحتياطي والتخزين' },
  ai: { en: 'AI', zh_CN: 'AI', zh_TW: 'AI', ja_JP: 'AI', ko_KR: 'AI', de_DE: 'KI', fr_FR: 'IA', es: 'IA', it_IT: 'IA', pt_PT: 'IA', ru_RU: 'ИИ', uk_UA: 'ШІ', tr_TR: 'Yapay zekâ', vi_VN: 'AI', ar: 'الذكاء الاصطناعي' },
  templates: { en: 'Config templates', zh_CN: '配置模板', zh_TW: '設定範本', ja_JP: '設定テンプレート', ko_KR: '설정 템플릿', de_DE: 'Konfigurationsvorlagen', fr_FR: 'Modèles de configuration', es: 'Plantillas de configuración', it_IT: 'Modelli di configurazione', pt_PT: 'Modelos de configuração', ru_RU: 'Шаблоны конфигурации', uk_UA: 'Шаблони конфігурації', tr_TR: 'Yapılandırma şablonları', vi_VN: 'Mẫu cấu hình', ar: 'قوالب الإعدادات' },
  languages: { en: 'Language packs', zh_CN: '语言包', zh_TW: '語言套件', ja_JP: '言語パック', ko_KR: '언어 팩', de_DE: 'Sprachpakete', fr_FR: 'Packs de langue', es: 'Paquetes de idioma', it_IT: 'Pacchetti di lingua', pt_PT: 'Pacotes de idioma', ru_RU: 'Языковые пакеты', uk_UA: 'Мовні пакети', tr_TR: 'Dil paketleri', vi_VN: 'Gói ngôn ngữ', ar: 'حزم اللغات' },
  integrations: { en: 'Integrations', zh_CN: '集成', zh_TW: '整合', ja_JP: '連携', ko_KR: '통합', de_DE: 'Integrationen', fr_FR: 'Intégrations', es: 'Integraciones', it_IT: 'Integrazioni', pt_PT: 'Integrações', ru_RU: 'Интеграции', uk_UA: 'Інтеграції', tr_TR: 'Entegrasyonlar', vi_VN: 'Tích hợp', ar: 'التكاملات' },
  tools: { en: 'Tools', zh_CN: '工具', zh_TW: '工具', ja_JP: 'ツール', ko_KR: '도구', de_DE: 'Werkzeuge', fr_FR: 'Outils', es: 'Herramientas', it_IT: 'Strumenti', pt_PT: 'Ferramentas', ru_RU: 'Инструменты', uk_UA: 'Інструменти', tr_TR: 'Araçlar', vi_VN: 'Công cụ', ar: 'الأدوات' },
}

export const CAPABILITIES = {
  'dns01': {
    label: { en: 'Certificate DNS validation', zh_CN: '证书 DNS 验证', zh_TW: '憑證 DNS 驗證', ja_JP: '証明書の DNS 検証', ko_KR: '인증서 DNS 검증', de_DE: 'DNS-Validierung von Zertifikaten', fr_FR: 'Validation DNS des certificats', es: 'Validación DNS de certificados', it_IT: 'Convalida DNS dei certificati', pt_PT: 'Validação DNS de certificados', ru_RU: 'DNS-проверка сертификатов', uk_UA: 'DNS-перевірка сертифікатів', tr_TR: 'Sertifika DNS doğrulaması', vi_VN: 'Xác thực DNS cho chứng chỉ', ar: 'التحقق من الشهادات عبر DNS' },
    description: { en: 'Validates domains through DNS records when certificates are issued or renewed.', zh_CN: '在签发或续期证书时通过 DNS 记录验证域名。', zh_TW: '在簽發或續期憑證時透過 DNS 記錄驗證網域。', ja_JP: '証明書の発行または更新時に DNS レコードでドメインを検証します。', ko_KR: '인증서를 발급하거나 갱신할 때 DNS 레코드로 도메인을 검증합니다.', de_DE: 'Validiert Domains über DNS-Einträge, wenn Zertifikate ausgestellt oder erneuert werden.', fr_FR: 'Valide les domaines par des enregistrements DNS lors de l\'émission ou du renouvellement des certificats.', es: 'Valida los dominios mediante registros DNS al emitir o renovar certificados.', it_IT: 'Convalida i domini tramite record DNS quando i certificati vengono emessi o rinnovati.', pt_PT: 'Valida os domínios através de registos DNS quando os certificados são emitidos ou renovados.', ru_RU: 'Проверяет домены через DNS-записи при выпуске или продлении сертификатов.', uk_UA: 'Перевіряє домени через DNS-записи під час випуску або поновлення сертифікатів.', tr_TR: 'Sertifikalar verilirken veya yenilenirken alan adlarını DNS kayıtlarıyla doğrular.', vi_VN: 'Xác thực tên miền bằng bản ghi DNS khi cấp hoặc gia hạn chứng chỉ.', ar: 'يتحقق من النطاقات عبر سجلات DNS عند إصدار الشهادات أو تجديدها.' },
  },
  'http': {
    label: { en: 'Web pages and API', zh_CN: '网页与 API', zh_TW: '網頁與 API', ja_JP: 'Web ページと API', ko_KR: '웹 페이지와 API', de_DE: 'Webseiten und API', fr_FR: 'Pages web et API', es: 'Páginas web y API', it_IT: 'Pagine web e API', pt_PT: 'Páginas web e API', ru_RU: 'Веб-страницы и API', uk_UA: 'Вебсторінки та API', tr_TR: 'Web sayfaları ve API', vi_VN: 'Trang web và API', ar: 'صفحات الويب وواجهة API' },
    description: { en: 'Serves its own pages and API inside Nginx UI.', zh_CN: '在 Nginx UI 中提供自己的页面和 API。', zh_TW: '在 Nginx UI 中提供自己的頁面和 API。', ja_JP: 'Nginx UI 内で独自のページと API を提供します。', ko_KR: 'Nginx UI 안에서 자체 페이지와 API를 제공합니다.', de_DE: 'Stellt eigene Seiten und eine eigene API in Nginx UI bereit.', fr_FR: 'Fournit ses propres pages et sa propre API dans Nginx UI.', es: 'Ofrece sus propias páginas y su propia API dentro de Nginx UI.', it_IT: 'Offre pagine e API proprie all\'interno di Nginx UI.', pt_PT: 'Disponibiliza páginas e uma API próprias no Nginx UI.', ru_RU: 'Предоставляет собственные страницы и API внутри Nginx UI.', uk_UA: 'Надає власні сторінки та API всередині Nginx UI.', tr_TR: 'Nginx UI içinde kendi sayfalarını ve API\'sini sunar.', vi_VN: 'Cung cấp trang và API riêng bên trong Nginx UI.', ar: 'يقدّم صفحاته وواجهة API الخاصة به داخل Nginx UI.' },
  },
  'notify': {
    label: { en: 'External notifications', zh_CN: '外部通知', zh_TW: '外部通知', ja_JP: '外部通知', ko_KR: '외부 알림', de_DE: 'Externe Benachrichtigungen', fr_FR: 'Notifications externes', es: 'Notificaciones externas', it_IT: 'Notifiche esterne', pt_PT: 'Notificações externas', ru_RU: 'Внешние уведомления', uk_UA: 'Зовнішні сповіщення', tr_TR: 'Harici bildirimler', vi_VN: 'Thông báo bên ngoài', ar: 'إشعارات خارجية' },
    description: { en: 'Delivers Nginx UI notifications to other services.', zh_CN: '将 Nginx UI 的通知发送到其他服务。', zh_TW: '將 Nginx UI 的通知傳送至其他服務。', ja_JP: 'Nginx UI の通知を他のサービスに配信します。', ko_KR: 'Nginx UI 알림을 다른 서비스로 전달합니다.', de_DE: 'Leitet Benachrichtigungen von Nginx UI an andere Dienste weiter.', fr_FR: 'Transmet les notifications de Nginx UI à d\'autres services.', es: 'Envía las notificaciones de Nginx UI a otros servicios.', it_IT: 'Inoltra le notifiche di Nginx UI ad altri servizi.', pt_PT: 'Envia as notificações do Nginx UI para outros serviços.', ru_RU: 'Доставляет уведомления Nginx UI в другие сервисы.', uk_UA: 'Доставляє сповіщення Nginx UI до інших сервісів.', tr_TR: 'Nginx UI bildirimlerini başka hizmetlere iletir.', vi_VN: 'Gửi thông báo của Nginx UI đến các dịch vụ khác.', ar: 'يوصل إشعارات Nginx UI إلى خدمات أخرى.' },
  },
  'probe': {
    label: { en: 'Health checks', zh_CN: '健康检查', zh_TW: '健康檢查', ja_JP: 'ヘルスチェック', ko_KR: '상태 확인', de_DE: 'Zustandsprüfungen', fr_FR: 'Contrôles d\'état', es: 'Comprobaciones de estado', it_IT: 'Controlli di stato', pt_PT: 'Verificações de estado', ru_RU: 'Проверки доступности', uk_UA: 'Перевірки доступності', tr_TR: 'Durum denetimleri', vi_VN: 'Kiểm tra tình trạng', ar: 'فحوص السلامة' },
    description: { en: 'Adds more ways to check whether sites and services are reachable.', zh_CN: '增加更多检查站点和服务是否可达的方式。', zh_TW: '增加更多檢查網站和服務是否可連線的方式。', ja_JP: 'サイトやサービスに到達できるかを確認する方法を追加します。', ko_KR: '사이트와 서비스에 접속할 수 있는지 확인하는 방법을 추가합니다.', de_DE: 'Fügt weitere Möglichkeiten hinzu, die Erreichbarkeit von Websites und Diensten zu prüfen.', fr_FR: 'Ajoute d\'autres moyens de vérifier que les sites et services sont joignables.', es: 'Añade más formas de comprobar si los sitios y servicios están accesibles.', it_IT: 'Aggiunge altri modi per verificare se siti e servizi sono raggiungibili.', pt_PT: 'Acrescenta mais formas de verificar se os sites e serviços estão acessíveis.', ru_RU: 'Добавляет способы проверить доступность сайтов и сервисов.', uk_UA: 'Додає способи перевірити доступність сайтів і сервісів.', tr_TR: 'Sitelerin ve hizmetlerin erişilebilir olup olmadığını denetlemek için yeni yollar ekler.', vi_VN: 'Thêm cách kiểm tra xem trang web và dịch vụ có truy cập được không.', ar: 'يضيف طرقًا أخرى للتحقق من إمكانية الوصول إلى المواقع والخدمات.' },
  },
  'mcp': {
    label: { en: 'AI assistant tools', zh_CN: 'AI 助手工具', zh_TW: 'AI 助理工具', ja_JP: 'AI アシスタントツール', ko_KR: 'AI 어시스턴트 도구', de_DE: 'Werkzeuge für KI-Assistenten', fr_FR: 'Outils pour assistants IA', es: 'Herramientas para asistentes de IA', it_IT: 'Strumenti per assistenti IA', pt_PT: 'Ferramentas para assistentes de IA', ru_RU: 'Инструменты для ИИ-ассистентов', uk_UA: 'Інструменти для ШІ-асистентів', tr_TR: 'Yapay zekâ asistanı araçları', vi_VN: 'Công cụ cho trợ lý AI', ar: 'أدوات مساعد الذكاء الاصطناعي' },
    description: { en: 'Offers actions that AI assistants connected to Nginx UI can run.', zh_CN: '提供可供连接到 Nginx UI 的 AI 助手执行的操作。', zh_TW: '提供可供連接到 Nginx UI 的 AI 助理執行的操作。', ja_JP: 'Nginx UI に接続された AI アシスタントが実行できる操作を提供します。', ko_KR: 'Nginx UI에 연결된 AI 어시스턴트가 실행할 수 있는 작업을 제공합니다.', de_DE: 'Bietet Aktionen, die mit Nginx UI verbundene KI-Assistenten ausführen können.', fr_FR: 'Propose des actions que les assistants IA connectés à Nginx UI peuvent exécuter.', es: 'Ofrece acciones que pueden ejecutar los asistentes de IA conectados a Nginx UI.', it_IT: 'Offre azioni che gli assistenti IA collegati a Nginx UI possono eseguire.', pt_PT: 'Disponibiliza ações que os assistentes de IA ligados ao Nginx UI podem executar.', ru_RU: 'Предоставляет действия, которые могут выполнять ИИ-ассистенты, подключённые к Nginx UI.', uk_UA: 'Надає дії, які можуть виконувати ШІ-асистенти, підключені до Nginx UI.', tr_TR: 'Nginx UI\'a bağlı yapay zekâ asistanlarının çalıştırabileceği eylemler sunar.', vi_VN: 'Cung cấp các thao tác mà trợ lý AI kết nối với Nginx UI có thể thực hiện.', ar: 'يوفّر إجراءات يمكن لمساعدي الذكاء الاصطناعي المتصلين بـ Nginx UI تنفيذها.' },
  },
  'storage': {
    label: { en: 'Backup storage', zh_CN: '备份存储', zh_TW: '備份儲存', ja_JP: 'バックアップストレージ', ko_KR: '백업 저장소', de_DE: 'Sicherungsspeicher', fr_FR: 'Stockage des sauvegardes', es: 'Almacenamiento de copias de seguridad', it_IT: 'Archiviazione dei backup', pt_PT: 'Armazenamento de cópias de segurança', ru_RU: 'Хранилище резервных копий', uk_UA: 'Сховище резервних копій', tr_TR: 'Yedekleme depolaması', vi_VN: 'Lưu trữ bản sao lưu', ar: 'تخزين النسخ الاحتياطية' },
    description: { en: 'Stores backups and other files in external storage.', zh_CN: '将备份和其他文件保存到外部存储。', zh_TW: '將備份和其他檔案儲存到外部儲存空間。', ja_JP: 'バックアップやその他のファイルを外部ストレージに保存します。', ko_KR: '백업과 기타 파일을 외부 저장소에 보관합니다.', de_DE: 'Speichert Sicherungen und andere Dateien in externem Speicher.', fr_FR: 'Stocke les sauvegardes et d\'autres fichiers dans un stockage externe.', es: 'Guarda las copias de seguridad y otros archivos en un almacenamiento externo.', it_IT: 'Salva i backup e altri file in un archivio esterno.', pt_PT: 'Guarda as cópias de segurança e outros ficheiros num armazenamento externo.', ru_RU: 'Сохраняет резервные копии и другие файлы во внешнем хранилище.', uk_UA: 'Зберігає резервні копії та інші файли в зовнішньому сховищі.', tr_TR: 'Yedekleri ve diğer dosyaları harici depolamada saklar.', vi_VN: 'Lưu bản sao lưu và các tệp khác vào bộ lưu trữ bên ngoài.', ar: 'يحفظ النسخ الاحتياطية والملفات الأخرى في تخزين خارجي.' },
  },
  'cert.deploy': {
    label: { en: 'Certificate deployment', zh_CN: '证书部署', zh_TW: '憑證部署', ja_JP: '証明書のデプロイ', ko_KR: '인증서 배포', de_DE: 'Zertifikatsbereitstellung', fr_FR: 'Déploiement des certificats', es: 'Despliegue de certificados', it_IT: 'Distribuzione dei certificati', pt_PT: 'Implementação de certificados', ru_RU: 'Развёртывание сертификатов', uk_UA: 'Розгортання сертифікатів', tr_TR: 'Sertifika dağıtımı', vi_VN: 'Triển khai chứng chỉ', ar: 'نشر الشهادات' },
    description: { en: 'Pushes issued certificates to other services and devices.', zh_CN: '将签发的证书推送到其他服务和设备。', zh_TW: '將簽發的憑證推送至其他服務和裝置。', ja_JP: '発行された証明書を他のサービスやデバイスへプッシュします。', ko_KR: '발급된 인증서를 다른 서비스와 기기로 전송합니다.', de_DE: 'Überträgt ausgestellte Zertifikate an andere Dienste und Geräte.', fr_FR: 'Envoie les certificats émis vers d\'autres services et appareils.', es: 'Envía los certificados emitidos a otros servicios y dispositivos.', it_IT: 'Invia i certificati emessi ad altri servizi e dispositivi.', pt_PT: 'Envia os certificados emitidos para outros serviços e dispositivos.', ru_RU: 'Передаёт выпущенные сертификаты в другие сервисы и на устройства.', uk_UA: 'Передає випущені сертифікати до інших сервісів і пристроїв.', tr_TR: 'Verilen sertifikaları başka hizmetlere ve cihazlara gönderir.', vi_VN: 'Đẩy chứng chỉ đã cấp đến các dịch vụ và thiết bị khác.', ar: 'يرسل الشهادات الصادرة إلى خدمات وأجهزة أخرى.' },
  },
  'security.blocklist': {
    label: { en: 'Blocklists', zh_CN: '封锁列表', zh_TW: '封鎖清單', ja_JP: 'ブロックリスト', ko_KR: '차단 목록', de_DE: 'Sperrlisten', fr_FR: 'Listes de blocage', es: 'Listas de bloqueo', it_IT: 'Elenchi di blocco', pt_PT: 'Listas de bloqueio', ru_RU: 'Списки блокировки', uk_UA: 'Списки блокування', tr_TR: 'Engelleme listeleri', vi_VN: 'Danh sách chặn', ar: 'قوائم الحظر' },
    description: { en: 'Keeps lists of addresses that are denied access up to date.', zh_CN: '持续更新禁止访问的地址列表。', zh_TW: '持續更新禁止存取的位址清單。', ja_JP: 'アクセスを拒否するアドレスのリストを最新に保ちます。', ko_KR: '접근이 거부되는 주소 목록을 최신 상태로 유지합니다.', de_DE: 'Hält Listen gesperrter Adressen auf dem neuesten Stand.', fr_FR: 'Tient à jour les listes d\'adresses dont l\'accès est refusé.', es: 'Mantiene actualizadas las listas de direcciones a las que se deniega el acceso.', it_IT: 'Mantiene aggiornati gli elenchi degli indirizzi a cui è negato l\'accesso.', pt_PT: 'Mantém atualizadas as listas de endereços aos quais o acesso é negado.', ru_RU: 'Поддерживает в актуальном состоянии списки адресов, которым запрещён доступ.', uk_UA: 'Підтримує в актуальному стані списки адрес, яким заборонено доступ.', tr_TR: 'Erişimi reddedilen adres listelerini güncel tutar.', vi_VN: 'Giữ danh sách các địa chỉ bị từ chối truy cập luôn cập nhật.', ar: 'يحدّث قوائم العناوين الممنوعة من الوصول باستمرار.' },
  },
  'upstream.discovery': {
    label: { en: 'Service discovery', zh_CN: '服务发现', zh_TW: '服務探索', ja_JP: 'サービスディスカバリー', ko_KR: '서비스 검색', de_DE: 'Diensterkennung', fr_FR: 'Découverte de services', es: 'Descubrimiento de servicios', it_IT: 'Rilevamento dei servizi', pt_PT: 'Descoberta de serviços', ru_RU: 'Обнаружение сервисов', uk_UA: 'Виявлення сервісів', tr_TR: 'Hizmet keşfi', vi_VN: 'Khám phá dịch vụ', ar: 'اكتشاف الخدمات' },
    description: { en: 'Finds backend servers automatically and keeps upstreams up to date.', zh_CN: '自动发现后端服务器，并保持 upstream 为最新状态。', zh_TW: '自動探索後端伺服器，並保持 upstream 為最新狀態。', ja_JP: 'バックエンドサーバーを自動的に検出し、upstream を最新に保ちます。', ko_KR: '백엔드 서버를 자동으로 찾고 upstream을 최신 상태로 유지합니다.', de_DE: 'Findet Backend-Server automatisch und hält Upstreams aktuell.', fr_FR: 'Trouve automatiquement les serveurs backend et tient les upstreams à jour.', es: 'Encuentra los servidores backend automáticamente y mantiene actualizados los upstreams.', it_IT: 'Trova automaticamente i server backend e mantiene aggiornati gli upstream.', pt_PT: 'Encontra automaticamente os servidores backend e mantém os upstreams atualizados.', ru_RU: 'Автоматически находит бэкенд-серверы и поддерживает upstream в актуальном состоянии.', uk_UA: 'Автоматично знаходить бекенд-сервери та підтримує upstream в актуальному стані.', tr_TR: 'Arka uç sunucularını otomatik olarak bulur ve upstream\'leri güncel tutar.', vi_VN: 'Tự động tìm máy chủ backend và giữ upstream luôn cập nhật.', ar: 'يعثر على الخوادم الخلفية تلقائيًا ويحدّث upstream باستمرار.' },
  },
  'log.sink': {
    label: { en: 'Access log forwarding', zh_CN: '访问日志转发', zh_TW: '存取日誌轉發', ja_JP: 'アクセスログの転送', ko_KR: '접근 로그 전달', de_DE: 'Weiterleitung von Zugriffsprotokollen', fr_FR: 'Transfert des journaux d\'accès', es: 'Reenvío de registros de acceso', it_IT: 'Inoltro dei log di accesso', pt_PT: 'Reencaminhamento dos registos de acesso', ru_RU: 'Пересылка журналов доступа', uk_UA: 'Пересилання журналів доступу', tr_TR: 'Erişim günlüğü iletimi', vi_VN: 'Chuyển tiếp nhật ký truy cập', ar: 'تمرير سجلات الوصول' },
    description: { en: 'Receives access log entries as they are written, for example to forward or analyse them.', zh_CN: '在访问日志写入时实时接收日志条目，例如用于转发或分析。', zh_TW: '在存取日誌寫入時即時接收日誌項目，例如用於轉發或分析。', ja_JP: 'アクセスログのエントリを書き込み時に受け取ります。転送や分析などに使用します。', ko_KR: '접근 로그 항목이 기록될 때 바로 받아 전달하거나 분석하는 등에 사용합니다.', de_DE: 'Empfängt Einträge des Zugriffsprotokolls beim Schreiben, etwa um sie weiterzuleiten oder zu analysieren.', fr_FR: 'Reçoit les entrées du journal d\'accès au fur et à mesure de leur écriture, par exemple pour les transférer ou les analyser.', es: 'Recibe las entradas del registro de acceso a medida que se escriben, por ejemplo para reenviarlas o analizarlas.', it_IT: 'Riceve le voci del log di accesso man mano che vengono scritte, ad esempio per inoltrarle o analizzarle.', pt_PT: 'Recebe as entradas do registo de acesso à medida que são escritas, por exemplo para as reencaminhar ou analisar.', ru_RU: 'Получает записи журнала доступа по мере их появления, например для пересылки или анализа.', uk_UA: 'Отримує записи журналу доступу в міру їх появи, наприклад для пересилання або аналізу.', tr_TR: 'Erişim günlüğü kayıtlarını yazıldıkları anda alır; örneğin iletmek veya analiz etmek için.', vi_VN: 'Nhận các mục nhật ký truy cập ngay khi được ghi, ví dụ để chuyển tiếp hoặc phân tích.', ar: 'يستقبل إدخالات سجل الوصول فور كتابتها، مثلًا لتمريرها أو تحليلها.' },
  },
}

export const OTHER_CAPABILITY = {
  label: { en: 'Other feature', zh_CN: '其他功能', zh_TW: '其他功能', ja_JP: 'その他の機能', ko_KR: '기타 기능', de_DE: 'Andere Funktion', fr_FR: 'Autre fonctionnalité', es: 'Otra función', it_IT: 'Altra funzione', pt_PT: 'Outra funcionalidade', ru_RU: 'Другая функция', uk_UA: 'Інша функція', tr_TR: 'Diğer özellik', vi_VN: 'Tính năng khác', ar: 'ميزة أخرى' },
  description: { en: 'A feature this version of Nginx UI does not describe.', zh_CN: '此版本的 Nginx UI 未描述的功能。', zh_TW: '此版本的 Nginx UI 未描述的功能。', ja_JP: 'このバージョンの Nginx UI では説明されていない機能です。', ko_KR: '이 버전의 Nginx UI에서 설명하지 않는 기능입니다.', de_DE: 'Eine Funktion, die diese Version von Nginx UI nicht beschreibt.', fr_FR: 'Une fonctionnalité que cette version de Nginx UI ne décrit pas.', es: 'Una función que esta versión de Nginx UI no describe.', it_IT: 'Una funzione che questa versione di Nginx UI non descrive.', pt_PT: 'Uma funcionalidade que esta versão do Nginx UI não descreve.', ru_RU: 'Функция, которую эта версия Nginx UI не описывает.', uk_UA: 'Функція, яку ця версія Nginx UI не описує.', tr_TR: 'Nginx UI\'ın bu sürümünün tanımlamadığı bir özellik.', vi_VN: 'Một tính năng mà phiên bản Nginx UI này không mô tả.', ar: 'ميزة لا يصفها هذا الإصدار من Nginx UI.' },
}

export const PERMISSIONS = {
  'kv': {
    label: { en: 'Own data storage', zh_CN: '自有数据存储', zh_TW: '自有資料儲存', ja_JP: '独自のデータストレージ', ko_KR: '자체 데이터 저장소', de_DE: 'Eigener Datenspeicher', fr_FR: 'Stockage de données propre', es: 'Almacenamiento de datos propio', it_IT: 'Archiviazione dati propria', pt_PT: 'Armazenamento de dados próprio', ru_RU: 'Собственное хранилище данных', uk_UA: 'Власне сховище даних', tr_TR: 'Kendi veri depolaması', vi_VN: 'Lưu trữ dữ liệu riêng', ar: 'تخزين بيانات خاص' },
    description: { en: 'Keep its own data inside Nginx UI.', zh_CN: '在 Nginx UI 中保存自己的数据。', zh_TW: '在 Nginx UI 中儲存自己的資料。', ja_JP: '独自のデータを Nginx UI 内に保存します。', ko_KR: 'Nginx UI 안에 자체 데이터를 보관합니다.', de_DE: 'Eigene Daten in Nginx UI speichern.', fr_FR: 'Conserver ses propres données dans Nginx UI.', es: 'Guardar sus propios datos dentro de Nginx UI.', it_IT: 'Conservare i propri dati all\'interno di Nginx UI.', pt_PT: 'Guardar os seus próprios dados no Nginx UI.', ru_RU: 'Хранить собственные данные внутри Nginx UI.', uk_UA: 'Зберігати власні дані всередині Nginx UI.', tr_TR: 'Kendi verilerini Nginx UI içinde saklamak.', vi_VN: 'Lưu dữ liệu riêng bên trong Nginx UI.', ar: 'حفظ بياناتها الخاصة داخل Nginx UI.' },
  },
  'network': {
    label: { en: 'Network', zh_CN: '网络', zh_TW: '網路', ja_JP: 'ネットワーク', ko_KR: '네트워크', de_DE: 'Netzwerk', fr_FR: 'Réseau', es: 'Red', it_IT: 'Rete', pt_PT: 'Rede', ru_RU: 'Сеть', uk_UA: 'Мережа', tr_TR: 'Ağ', vi_VN: 'Mạng', ar: 'الشبكة' },
    description: { en: 'Connect to other servers over the network.', zh_CN: '通过网络连接到其他服务器。', zh_TW: '透過網路連線到其他伺服器。', ja_JP: 'ネットワーク経由で他のサーバーに接続します。', ko_KR: '네트워크를 통해 다른 서버에 연결합니다.', de_DE: 'Über das Netzwerk eine Verbindung zu anderen Servern herstellen.', fr_FR: 'Se connecter à d\'autres serveurs par le réseau.', es: 'Conectarse a otros servidores a través de la red.', it_IT: 'Connettersi ad altri server tramite la rete.', pt_PT: 'Ligar-se a outros servidores através da rede.', ru_RU: 'Подключаться к другим серверам по сети.', uk_UA: 'Підключатися до інших серверів через мережу.', tr_TR: 'Ağ üzerinden başka sunuculara bağlanmak.', vi_VN: 'Kết nối đến các máy chủ khác qua mạng.', ar: 'الاتصال بخوادم أخرى عبر الشبكة.' },
  },
  'cron': {
    label: { en: 'Scheduled tasks', zh_CN: '计划任务', zh_TW: '排程任務', ja_JP: 'スケジュールタスク', ko_KR: '예약 작업', de_DE: 'Geplante Aufgaben', fr_FR: 'Tâches planifiées', es: 'Tareas programadas', it_IT: 'Attività pianificate', pt_PT: 'Tarefas agendadas', ru_RU: 'Запланированные задачи', uk_UA: 'Заплановані завдання', tr_TR: 'Zamanlanmış görevler', vi_VN: 'Tác vụ theo lịch', ar: 'المهام المجدولة' },
    description: { en: 'Run tasks on a regular schedule.', zh_CN: '按固定计划执行任务。', zh_TW: '依固定排程執行任務。', ja_JP: '定期的なスケジュールでタスクを実行します。', ko_KR: '정해진 일정에 따라 작업을 실행합니다.', de_DE: 'Aufgaben nach einem festen Zeitplan ausführen.', fr_FR: 'Exécuter des tâches selon un calendrier régulier.', es: 'Ejecutar tareas según una programación periódica.', it_IT: 'Eseguire attività secondo una pianificazione regolare.', pt_PT: 'Executar tarefas segundo um agendamento regular.', ru_RU: 'Выполнять задачи по расписанию.', uk_UA: 'Виконувати завдання за розкладом.', tr_TR: 'Görevleri düzenli bir zamanlamayla çalıştırmak.', vi_VN: 'Chạy tác vụ theo lịch định kỳ.', ar: 'تشغيل المهام وفق جدول منتظم.' },
  },
  'notify': {
    label: { en: 'Notifications', zh_CN: '通知', zh_TW: '通知', ja_JP: '通知', ko_KR: '알림', de_DE: 'Benachrichtigungen', fr_FR: 'Notifications', es: 'Notificaciones', it_IT: 'Notifiche', pt_PT: 'Notificações', ru_RU: 'Уведомления', uk_UA: 'Сповіщення', tr_TR: 'Bildirimler', vi_VN: 'Thông báo', ar: 'الإشعارات' },
    description: { en: 'Send notifications through the Nginx UI notification channels.', zh_CN: '通过 Nginx UI 的通知渠道发送通知。', zh_TW: '透過 Nginx UI 的通知管道發送通知。', ja_JP: 'Nginx UI の通知チャネルを通じて通知を送信します。', ko_KR: 'Nginx UI 알림 채널을 통해 알림을 보냅니다.', de_DE: 'Benachrichtigungen über die Benachrichtigungskanäle von Nginx UI senden.', fr_FR: 'Envoyer des notifications par les canaux de notification de Nginx UI.', es: 'Enviar notificaciones a través de los canales de notificación de Nginx UI.', it_IT: 'Inviare notifiche tramite i canali di notifica di Nginx UI.', pt_PT: 'Enviar notificações através dos canais de notificação do Nginx UI.', ru_RU: 'Отправлять уведомления через каналы уведомлений Nginx UI.', uk_UA: 'Надсилати сповіщення через канали сповіщень Nginx UI.', tr_TR: 'Nginx UI bildirim kanalları üzerinden bildirim göndermek.', vi_VN: 'Gửi thông báo qua các kênh thông báo của Nginx UI.', ar: 'إرسال الإشعارات عبر قنوات الإشعارات في Nginx UI.' },
  },
  'metrics.read': {
    label: { en: 'Server metrics', zh_CN: '服务器指标', zh_TW: '伺服器指標', ja_JP: 'サーバーメトリクス', ko_KR: '서버 지표', de_DE: 'Servermetriken', fr_FR: 'Métriques du serveur', es: 'Métricas del servidor', it_IT: 'Metriche del server', pt_PT: 'Métricas do servidor', ru_RU: 'Метрики сервера', uk_UA: 'Метрики сервера', tr_TR: 'Sunucu ölçümleri', vi_VN: 'Chỉ số máy chủ', ar: 'مقاييس الخادم' },
    description: { en: 'Read CPU, memory, network and Nginx status metrics of this node.', zh_CN: '读取本节点的 CPU、内存、网络及 Nginx 状态指标。', zh_TW: '讀取此節點的 CPU、記憶體、網路及 Nginx 狀態指標。', ja_JP: 'このノードの CPU、メモリ、ネットワーク、Nginx のステータス指標を読み取ります。', ko_KR: '이 노드의 CPU, 메모리, 네트워크 및 Nginx 상태 지표를 읽습니다.', de_DE: 'CPU-, Speicher-, Netzwerk- und Nginx-Statusmetriken dieses Knotens lesen.', fr_FR: 'Lire les métriques de processeur, de mémoire, de réseau et d\'état de Nginx de ce nœud.', es: 'Leer las métricas de CPU, memoria, red y estado de Nginx de este nodo.', it_IT: 'Leggere le metriche di CPU, memoria, rete e stato di Nginx di questo nodo.', pt_PT: 'Ler as métricas de CPU, memória, rede e estado do Nginx deste nó.', ru_RU: 'Читать метрики CPU, памяти, сети и состояния Nginx этого узла.', uk_UA: 'Читати метрики CPU, пам\'яті, мережі та стану Nginx цього вузла.', tr_TR: 'Bu düğümün CPU, bellek, ağ ve Nginx durum ölçümlerini okumak.', vi_VN: 'Đọc các chỉ số CPU, bộ nhớ, mạng và trạng thái Nginx của nút này.', ar: 'قراءة مقاييس المعالج والذاكرة والشبكة وحالة Nginx لهذه العقدة.' },
  },
  'core_api': {
    label: { en: 'Nginx UI management', zh_CN: 'Nginx UI 管理', zh_TW: 'Nginx UI 管理', ja_JP: 'Nginx UI の管理', ko_KR: 'Nginx UI 관리', de_DE: 'Verwaltung von Nginx UI', fr_FR: 'Gestion de Nginx UI', es: 'Administración de Nginx UI', it_IT: 'Gestione di Nginx UI', pt_PT: 'Gestão do Nginx UI', ru_RU: 'Управление Nginx UI', uk_UA: 'Керування Nginx UI', tr_TR: 'Nginx UI yönetimi', vi_VN: 'Quản lý Nginx UI', ar: 'إدارة Nginx UI' },
    description: { en: 'Manage Nginx UI with your permissions.', zh_CN: '以您的权限管理 Nginx UI。', zh_TW: '以您的權限管理 Nginx UI。', ja_JP: 'あなたの権限で Nginx UI を管理します。', ko_KR: '사용자의 권한으로 Nginx UI를 관리합니다.', de_DE: 'Nginx UI mit Ihren Berechtigungen verwalten.', fr_FR: 'Gérer Nginx UI avec vos autorisations.', es: 'Administrar Nginx UI con sus permisos.', it_IT: 'Gestire Nginx UI con le proprie autorizzazioni.', pt_PT: 'Gerir o Nginx UI com as suas permissões.', ru_RU: 'Управлять Nginx UI с вашими правами.', uk_UA: 'Керувати Nginx UI з вашими правами.', tr_TR: 'Nginx UI\'ı sizin izinlerinizle yönetmek.', vi_VN: 'Quản lý Nginx UI bằng quyền của bạn.', ar: 'إدارة Nginx UI بصلاحياتك.' },
  },
  'mcp': {
    label: { en: 'AI assistant tools', zh_CN: 'AI 助手工具', zh_TW: 'AI 助理工具', ja_JP: 'AI アシスタントツール', ko_KR: 'AI 어시스턴트 도구', de_DE: 'Werkzeuge für KI-Assistenten', fr_FR: 'Outils pour assistants IA', es: 'Herramientas para asistentes de IA', it_IT: 'Strumenti per assistenti IA', pt_PT: 'Ferramentas para assistentes de IA', ru_RU: 'Инструменты для ИИ-ассистентов', uk_UA: 'Інструменти для ШІ-асистентів', tr_TR: 'Yapay zekâ asistanı araçları', vi_VN: 'Công cụ cho trợ lý AI', ar: 'أدوات مساعد الذكاء الاصطناعي' },
    description: { en: 'Offer actions that AI assistants connected to Nginx UI can run.', zh_CN: '提供可供连接到 Nginx UI 的 AI 助手执行的操作。', zh_TW: '提供可供連接到 Nginx UI 的 AI 助理執行的操作。', ja_JP: 'Nginx UI に接続された AI アシスタントが実行できる操作を提供します。', ko_KR: 'Nginx UI에 연결된 AI 어시스턴트가 실행할 수 있는 작업을 제공합니다.', de_DE: 'Aktionen bereitstellen, die mit Nginx UI verbundene KI-Assistenten ausführen können.', fr_FR: 'Proposer des actions que les assistants IA connectés à Nginx UI peuvent exécuter.', es: 'Ofrecer acciones que pueden ejecutar los asistentes de IA conectados a Nginx UI.', it_IT: 'Offrire azioni che gli assistenti IA collegati a Nginx UI possono eseguire.', pt_PT: 'Disponibilizar ações que os assistentes de IA ligados ao Nginx UI podem executar.', ru_RU: 'Предоставлять действия, которые могут выполнять ИИ-ассистенты, подключённые к Nginx UI.', uk_UA: 'Надавати дії, які можуть виконувати ШІ-асистенти, підключені до Nginx UI.', tr_TR: 'Nginx UI\'a bağlı yapay zekâ asistanlarının çalıştırabileceği eylemler sunmak.', vi_VN: 'Cung cấp các thao tác mà trợ lý AI kết nối với Nginx UI có thể thực hiện.', ar: 'توفير إجراءات يمكن لمساعدي الذكاء الاصطناعي المتصلين بـ Nginx UI تنفيذها.' },
  },
  'cert.deploy': {
    label: { en: 'Certificates', zh_CN: '证书', zh_TW: '憑證', ja_JP: '証明書', ko_KR: '인증서', de_DE: 'Zertifikate', fr_FR: 'Certificats', es: 'Certificados', it_IT: 'Certificati', pt_PT: 'Certificados', ru_RU: 'Сертификаты', uk_UA: 'Сертифікати', tr_TR: 'Sertifikalar', vi_VN: 'Chứng chỉ', ar: 'الشهادات' },
    description: { en: 'Receive issued certificates, including the parts that must stay secret, to push them to other services.', zh_CN: '接收签发的证书（包括必须保密的部分），以推送到其他服务。', zh_TW: '接收簽發的憑證（包括必須保密的部分），以推送至其他服務。', ja_JP: '発行された証明書を、秘密にすべき部分も含めて受け取り、他のサービスへプッシュします。', ko_KR: '발급된 인증서를 비밀로 유지해야 하는 부분까지 포함해 받아 다른 서비스로 전송합니다.', de_DE: 'Ausgestellte Zertifikate einschließlich der geheim zu haltenden Teile empfangen, um sie an andere Dienste zu übertragen.', fr_FR: 'Recevoir les certificats émis, y compris les parties qui doivent rester secrètes, pour les envoyer vers d\'autres services.', es: 'Recibir los certificados emitidos, incluidas las partes que deben permanecer secretas, para enviarlos a otros servicios.', it_IT: 'Ricevere i certificati emessi, comprese le parti che devono restare segrete, per inviarli ad altri servizi.', pt_PT: 'Receber os certificados emitidos, incluindo as partes que têm de permanecer secretas, para os enviar para outros serviços.', ru_RU: 'Получать выпущенные сертификаты, включая части, которые должны оставаться секретными, чтобы передавать их в другие сервисы.', uk_UA: 'Отримувати випущені сертифікати, включно з частинами, що мають залишатися секретними, щоб передавати їх до інших сервісів.', tr_TR: 'Verilen sertifikaları, gizli kalması gereken kısımları dahil, başka hizmetlere göndermek için almak.', vi_VN: 'Nhận chứng chỉ đã cấp, bao gồm cả các phần phải giữ bí mật, để đẩy đến các dịch vụ khác.', ar: 'استلام الشهادات الصادرة، بما في ذلك الأجزاء التي يجب أن تبقى سرية، لإرسالها إلى خدمات أخرى.' },
  },
  'log.read': {
    label: { en: 'Access logs', zh_CN: '访问日志', zh_TW: '存取日誌', ja_JP: 'アクセスログ', ko_KR: '접근 로그', de_DE: 'Zugriffsprotokolle', fr_FR: 'Journaux d\'accès', es: 'Registros de acceso', it_IT: 'Log di accesso', pt_PT: 'Registos de acesso', ru_RU: 'Журналы доступа', uk_UA: 'Журнали доступу', tr_TR: 'Erişim günlükleri', vi_VN: 'Nhật ký truy cập', ar: 'سجلات الوصول' },
    description: { en: 'Receive every access log entry while it is on, including visitor addresses and requested URLs.', zh_CN: '开启期间接收每条访问日志，包括访客地址和请求的 URL。', zh_TW: '開啟期間接收每筆存取日誌，包括訪客位址和請求的 URL。', ja_JP: 'オンの間、訪問者のアドレスやリクエストされた URL を含むすべてのアクセスログを受け取ります。', ko_KR: '켜져 있는 동안 방문자 주소와 요청 URL을 포함한 모든 접근 로그 항목을 받습니다.', de_DE: 'Solange eingeschaltet, jeden Eintrag des Zugriffsprotokolls empfangen, einschließlich Besucheradressen und angeforderter URLs.', fr_FR: 'Tant qu\'il est activé, recevoir chaque entrée du journal d\'accès, y compris les adresses des visiteurs et les URL demandées.', es: 'Mientras está activado, recibir cada entrada del registro de acceso, incluidas las direcciones de los visitantes y las URL solicitadas.', it_IT: 'Finché è attivo, ricevere ogni voce del log di accesso, compresi gli indirizzi dei visitatori e gli URL richiesti.', pt_PT: 'Enquanto estiver ativo, receber cada entrada do registo de acesso, incluindo os endereços dos visitantes e os URL pedidos.', ru_RU: 'Пока включено, получать каждую запись журнала доступа, включая адреса посетителей и запрошенные URL.', uk_UA: 'Поки ввімкнено, отримувати кожен запис журналу доступу, включно з адресами відвідувачів і запитаними URL.', tr_TR: 'Açık olduğu sürece ziyaretçi adresleri ve istenen URL\'ler dahil her erişim günlüğü kaydını almak.', vi_VN: 'Trong khi bật, nhận mọi mục nhật ký truy cập, bao gồm địa chỉ khách truy cập và URL được yêu cầu.', ar: 'استلام كل إدخال في سجل الوصول طوال مدة التفعيل، بما في ذلك عناوين الزوار وعناوين URL المطلوبة.' },
  },
  'log.files': {
    label: { en: 'Log files', zh_CN: '日志文件', zh_TW: '日誌檔案', ja_JP: 'ログファイル', ko_KR: '로그 파일', de_DE: 'Protokolldateien', fr_FR: 'Fichiers journaux', es: 'Archivos de registro', it_IT: 'File di log', pt_PT: 'Ficheiros de registo', ru_RU: 'Файлы журналов', uk_UA: 'Файли журналів', tr_TR: 'Günlük dosyaları', vi_VN: 'Tệp nhật ký', ar: 'ملفات السجلات' },
    description: { en: 'Read the Nginx log files of this node, including visitor addresses and requested URLs.', zh_CN: '读取此节点的 Nginx 日志文件，其中包含访客地址和请求的 URL。', zh_TW: '讀取此節點的 Nginx 日誌檔案，其中包含訪客位址和請求的 URL。', ja_JP: 'このノードの Nginx ログファイルを読み取ります。訪問者のアドレスやリクエストされた URL が含まれます。', ko_KR: '방문자 주소와 요청 URL이 포함된 이 노드의 Nginx 로그 파일을 읽습니다.', de_DE: 'Die Nginx-Protokolldateien dieses Knotens lesen, einschließlich Besucheradressen und angeforderter URLs.', fr_FR: 'Lire les fichiers journaux Nginx de ce nœud, y compris les adresses des visiteurs et les URL demandées.', es: 'Leer los archivos de registro de Nginx de este nodo, incluidas las direcciones de los visitantes y las URL solicitadas.', it_IT: 'Leggere i file di log di Nginx di questo nodo, compresi gli indirizzi dei visitatori e gli URL richiesti.', pt_PT: 'Ler os ficheiros de registo do Nginx deste nó, incluindo os endereços dos visitantes e os URL pedidos.', ru_RU: 'Читать файлы журналов Nginx этого узла, включая адреса посетителей и запрошенные URL.', uk_UA: 'Читати файли журналів Nginx цього вузла, включно з адресами відвідувачів і запитаними URL.', tr_TR: 'Ziyaretçi adresleri ve istenen URL\'ler dahil bu düğümün Nginx günlük dosyalarını okumak.', vi_VN: 'Đọc các tệp nhật ký Nginx của nút này, bao gồm địa chỉ khách truy cập và URL được yêu cầu.', ar: 'قراءة ملفات سجلات Nginx لهذه العقدة، بما في ذلك عناوين الزوار وعناوين URL المطلوبة.' },
  },
  'nginx.snippet': {
    label: { en: 'Nginx configuration snippets', zh_CN: 'Nginx 配置片段', zh_TW: 'Nginx 設定片段', ja_JP: 'Nginx 設定スニペット', ko_KR: 'Nginx 설정 조각', de_DE: 'Nginx-Konfigurationsausschnitte', fr_FR: 'Extraits de configuration Nginx', es: 'Fragmentos de configuración de Nginx', it_IT: 'Frammenti di configurazione Nginx', pt_PT: 'Fragmentos de configuração do Nginx', ru_RU: 'Фрагменты конфигурации Nginx', uk_UA: 'Фрагменти конфігурації Nginx', tr_TR: 'Nginx yapılandırma parçacıkları', vi_VN: 'Đoạn cấu hình Nginx', ar: 'مقتطفات إعدادات Nginx' },
    description: { en: 'Add Nginx configuration of its own. It takes effect only where you include it, and Nginx UI applies it only when the configuration remains valid.', zh_CN: '添加它自己的 Nginx 配置。配置只在你引入它的位置生效，且只有在整体配置仍然有效时，Nginx UI 才会应用它。', zh_TW: '新增它自己的 Nginx 設定。設定只在你引入它的位置生效，且只有在整體設定仍然有效時，Nginx UI 才會套用它。', ja_JP: '独自の Nginx 設定を追加します。設定は読み込んだ場所でのみ有効になり、Nginx UI は設定全体が有効な場合にのみ適用します。', ko_KR: '자체 Nginx 설정을 추가합니다. 설정은 사용자가 포함한 위치에서만 적용되며, Nginx UI는 전체 설정이 유효할 때만 적용합니다.', de_DE: 'Eigene Nginx-Konfiguration hinzufügen. Sie wirkt nur dort, wo Sie sie einbinden, und Nginx UI übernimmt sie nur, wenn die Konfiguration gültig bleibt.', fr_FR: 'Ajouter sa propre configuration Nginx. Elle ne s\'applique que là où vous l\'incluez, et Nginx UI ne l\'applique que si la configuration reste valide.', es: 'Añadir su propia configuración de Nginx. Solo tiene efecto donde usted la incluya, y Nginx UI solo la aplica si la configuración sigue siendo válida.', it_IT: 'Aggiungere una propria configurazione Nginx. Ha effetto solo dove viene inclusa e Nginx UI la applica solo se la configurazione resta valida.', pt_PT: 'Adicionar a sua própria configuração do Nginx. Só tem efeito onde a incluir e o Nginx UI só a aplica se a configuração continuar válida.', ru_RU: 'Добавлять собственную конфигурацию Nginx. Она действует только там, где вы её подключите, а Nginx UI применяет её, только если конфигурация остаётся корректной.', uk_UA: 'Додавати власну конфігурацію Nginx. Вона діє лише там, де ви її підключите, а Nginx UI застосовує її, лише якщо конфігурація лишається коректною.', tr_TR: 'Kendi Nginx yapılandırmasını eklemek. Yalnızca sizin dahil ettiğiniz yerde etkili olur ve Nginx UI bunu yalnızca yapılandırma geçerli kaldığında uygular.', vi_VN: 'Thêm cấu hình Nginx riêng. Cấu hình chỉ có hiệu lực ở nơi bạn đưa vào, và Nginx UI chỉ áp dụng khi cấu hình vẫn hợp lệ.', ar: 'إضافة إعدادات Nginx خاصة بها. لا تسري إلا حيث تضمّنها، ولا يطبّقها Nginx UI إلا إذا بقيت الإعدادات صالحة.' },
  },
  'nginx.config.read': {
    label: { en: 'Nginx configuration', zh_CN: 'Nginx 配置', zh_TW: 'Nginx 設定', ja_JP: 'Nginx 設定', ko_KR: 'Nginx 설정', de_DE: 'Nginx-Konfiguration', fr_FR: 'Configuration Nginx', es: 'Configuración de Nginx', it_IT: 'Configurazione Nginx', pt_PT: 'Configuração do Nginx', ru_RU: 'Конфигурация Nginx', uk_UA: 'Конфігурація Nginx', tr_TR: 'Nginx yapılandırması', vi_VN: 'Cấu hình Nginx', ar: 'إعدادات Nginx' },
    description: { en: 'Read the Nginx configuration files of this node.', zh_CN: '读取此节点的 Nginx 配置文件。', zh_TW: '讀取此節點的 Nginx 設定檔。', ja_JP: 'このノードの Nginx 設定ファイルを読み取ります。', ko_KR: '이 노드의 Nginx 설정 파일을 읽습니다.', de_DE: 'Die Nginx-Konfigurationsdateien dieses Knotens lesen.', fr_FR: 'Lire les fichiers de configuration Nginx de ce nœud.', es: 'Leer los archivos de configuración de Nginx de este nodo.', it_IT: 'Leggere i file di configurazione di Nginx di questo nodo.', pt_PT: 'Ler os ficheiros de configuração do Nginx deste nó.', ru_RU: 'Читать файлы конфигурации Nginx этого узла.', uk_UA: 'Читати файли конфігурації Nginx цього вузла.', tr_TR: 'Bu düğümün Nginx yapılandırma dosyalarını okumak.', vi_VN: 'Đọc các tệp cấu hình Nginx của nút này.', ar: 'قراءة ملفات إعدادات Nginx لهذه العقدة.' },
  },
  'sites.read': {
    label: { en: 'Sites', zh_CN: '站点', zh_TW: '站點', ja_JP: 'サイト', ko_KR: '사이트', de_DE: 'Websites', fr_FR: 'Sites', es: 'Sitios', it_IT: 'Siti', pt_PT: 'Sites', ru_RU: 'Сайты', uk_UA: 'Сайти', tr_TR: 'Siteler', vi_VN: 'Trang web', ar: 'المواقع' },
    description: { en: 'See the sites of this node and their addresses.', zh_CN: '查看此节点的站点及其地址。', zh_TW: '檢視此節點的站點及其位址。', ja_JP: 'このノードのサイトとそのアドレスを表示します。', ko_KR: '이 노드의 사이트와 주소를 확인합니다.', de_DE: 'Die Websites dieses Knotens und ihre Adressen sehen.', fr_FR: 'Voir les sites de ce nœud et leurs adresses.', es: 'Ver los sitios de este nodo y sus direcciones.', it_IT: 'Vedere i siti di questo nodo e i loro indirizzi.', pt_PT: 'Ver os sites deste nó e os respetivos endereços.', ru_RU: 'Видеть сайты этого узла и их адреса.', uk_UA: 'Бачити сайти цього вузла та їхні адреси.', tr_TR: 'Bu düğümün sitelerini ve adreslerini görmek.', vi_VN: 'Xem các trang web của nút này và địa chỉ của chúng.', ar: 'رؤية مواقع هذه العقدة وعناوينها.' },
  },
  'certs.read': {
    label: { en: 'Certificate list', zh_CN: '证书列表', zh_TW: '憑證清單', ja_JP: '証明書一覧', ko_KR: '인증서 목록', de_DE: 'Zertifikatsliste', fr_FR: 'Liste des certificats', es: 'Lista de certificados', it_IT: 'Elenco dei certificati', pt_PT: 'Lista de certificados', ru_RU: 'Список сертификатов', uk_UA: 'Список сертифікатів', tr_TR: 'Sertifika listesi', vi_VN: 'Danh sách chứng chỉ', ar: 'قائمة الشهادات' },
    description: { en: 'See the certificates and when they expire, without the parts that must stay secret.', zh_CN: '查看证书及其到期时间，不包括必须保密的部分。', zh_TW: '檢視憑證及其到期時間，不包括必須保密的部分。', ja_JP: '秘密にすべき部分を除き、証明書とその有効期限を表示します。', ko_KR: '비밀로 유지해야 하는 부분을 제외하고 인증서와 만료 시기를 확인합니다.', de_DE: 'Die Zertifikate und ihr Ablaufdatum sehen, ohne die geheim zu haltenden Teile.', fr_FR: 'Voir les certificats et leur date d\'expiration, sans les parties qui doivent rester secrètes.', es: 'Ver los certificados y cuándo caducan, sin las partes que deben permanecer secretas.', it_IT: 'Vedere i certificati e la loro scadenza, senza le parti che devono restare segrete.', pt_PT: 'Ver os certificados e quando expiram, sem as partes que têm de permanecer secretas.', ru_RU: 'Видеть сертификаты и сроки их действия, без частей, которые должны оставаться секретными.', uk_UA: 'Бачити сертифікати та строки їхньої дії, без частин, що мають залишатися секретними.', tr_TR: 'Gizli kalması gereken kısımlar olmadan sertifikaları ve son kullanma tarihlerini görmek.', vi_VN: 'Xem các chứng chỉ và thời điểm hết hạn, không bao gồm các phần phải giữ bí mật.', ar: 'رؤية الشهادات وموعد انتهائها، دون الأجزاء التي يجب أن تبقى سرية.' },
  },
}

/** credentials.read:<kind>, the kind filled in. */
export const CREDENTIALS_PERMISSION = {
  label: { en: kind => `Stored ${kind} credentials`, zh_CN: kind => `已保存的 ${kind} 凭证`, zh_TW: kind => `已儲存的 ${kind} 憑證`, ja_JP: kind => `保存されている ${kind} の資格情報`, ko_KR: kind => `저장된 ${kind} 자격 증명`, de_DE: kind => `Gespeicherte ${kind}-Zugangsdaten`, fr_FR: kind => `Identifiants ${kind} enregistrés`, es: kind => `Credenciales de ${kind} guardadas`, it_IT: kind => `Credenziali ${kind} salvate`, pt_PT: kind => `Credenciais de ${kind} guardadas`, ru_RU: kind => `Сохранённые учётные данные ${kind}`, uk_UA: kind => `Збережені облікові дані ${kind}`, tr_TR: kind => `Kayıtlı ${kind} kimlik bilgileri`, vi_VN: kind => `Thông tin xác thực ${kind} đã lưu`, ar: kind => `بيانات اعتماد ${kind} المحفوظة` },
  description: { en: kind => `Read stored ${kind} credentials, including their secrets.`, zh_CN: kind => `读取已保存的 ${kind} 凭据，包括其密钥。`, zh_TW: kind => `讀取已儲存的 ${kind} 憑證，包括其密鑰。`, ja_JP: kind => `保存されている ${kind} の資格情報を、シークレットを含めて読み取ります。`, ko_KR: kind => `저장된 ${kind} 자격 증명을 비밀 정보까지 포함해 읽습니다.`, de_DE: kind => `Gespeicherte ${kind}-Zugangsdaten einschließlich ihrer Geheimnisse lesen.`, fr_FR: kind => `Lire les identifiants ${kind} enregistrés, y compris leurs secrets.`, es: kind => `Leer las credenciales de ${kind} guardadas, incluidos sus secretos.`, it_IT: kind => `Leggere le credenziali ${kind} salvate, compresi i relativi segreti.`, pt_PT: kind => `Ler as credenciais de ${kind} guardadas, incluindo os respetivos segredos.`, ru_RU: kind => `Читать сохранённые учётные данные ${kind}, включая секреты.`, uk_UA: kind => `Читати збережені облікові дані ${kind}, включно із секретами.`, tr_TR: kind => `Kayıtlı ${kind} kimlik bilgilerini gizli değerleri dahil okumak.`, vi_VN: kind => `Đọc thông tin xác thực ${kind} đã lưu, bao gồm cả phần bí mật.`, ar: kind => `قراءة بيانات اعتماد ${kind} المحفوظة، بما في ذلك أسرارها.` },
}

export const UNKNOWN_PERMISSION = {
  label: { en: 'Unknown permission', zh_CN: '未知权限', zh_TW: '未知權限', ja_JP: '不明な権限', ko_KR: '알 수 없는 권한', de_DE: 'Unbekannte Berechtigung', fr_FR: 'Autorisation inconnue', es: 'Permiso desconocido', it_IT: 'Autorizzazione sconosciuta', pt_PT: 'Permissão desconhecida', ru_RU: 'Неизвестное разрешение', uk_UA: 'Невідомий дозвіл', tr_TR: 'Bilinmeyen izin', vi_VN: 'Quyền không xác định', ar: 'إذن غير معروف' },
  description: { en: 'Unknown permission. Only grant it if you trust the plugin author.', zh_CN: '未知权限，请仅在信任插件作者时授予。', zh_TW: '未知權限，請僅在信任外掛作者時授予。', ja_JP: '不明な権限です。プラグインの作者を信頼できる場合のみ許可してください。', ko_KR: '알 수 없는 권한입니다. 플러그인 작성자를 신뢰하는 경우에만 허용하십시오.', de_DE: 'Unbekannte Berechtigung. Erteilen Sie sie nur, wenn Sie dem Autor des Plugins vertrauen.', fr_FR: 'Autorisation inconnue. Ne l\'accordez que si vous faites confiance à l\'auteur du plugin.', es: 'Permiso desconocido. Concédalo solo si confía en el autor del plugin.', it_IT: 'Autorizzazione sconosciuta. Concederla solo se ci si fida dell\'autore del plugin.', pt_PT: 'Permissão desconhecida. Conceda-a apenas se confiar no autor do plugin.', ru_RU: 'Неизвестное разрешение. Предоставляйте его, только если доверяете автору плагина.', uk_UA: 'Невідомий дозвіл. Надавайте його, лише якщо довіряєте авторові плагіна.', tr_TR: 'Bilinmeyen izin. Yalnızca eklentinin geliştiricisine güveniyorsanız verin.', vi_VN: 'Quyền không xác định. Chỉ cấp nếu bạn tin tưởng tác giả của plugin.', ar: 'إذن غير معروف. لا تمنحه إلا إذا كنت تثق بمطوّر الإضافة.' },
}
